{{:name "test1", :type :config-resource/topic}
 {"min.insync.replicas"
  {:name "min.insync.replicas",
   :value "1",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "follower.replication.throttled.replicas"
  {:name "follower.replication.throttled.replicas",
   :value "",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "flush.messages"
  {:name "flush.messages",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "leader.replication.throttled.replicas"
  {:name "leader.replication.throttled.replicas",
   :value "",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.bytes"
  {:name "segment.bytes",
   :value "1073741824",
   :default? false,
   :read-only? false,
   :sensitive? false},
  "flush.ms"
  {:name "flush.ms",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "unclean.leader.election.enable"
  {:name "unclean.leader.election.enable",
   :value "false",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "retention.bytes"
  {:name "retention.bytes",
   :value "-1",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "cleanup.policy"
  {:name "cleanup.policy",
   :value "compact",
   :default? false,
   :read-only? false,
   :sensitive? false},
  "file.delete.delay.ms"
  {:name "file.delete.delay.ms",
   :value "60000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.index.bytes"
  {:name "segment.index.bytes",
   :value "10485760",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "index.interval.bytes"
  {:name "index.interval.bytes",
   :value "4096",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "delete.retention.ms"
  {:name "delete.retention.ms",
   :value "86400000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.ms"
  {:name "segment.ms",
   :value "604800000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "min.compaction.lag.ms"
  {:name "min.compaction.lag.ms",
   :value "0",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.jitter.ms"
  {:name "segment.jitter.ms",
   :value "0",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.timestamp.difference.max.ms"
  {:name "message.timestamp.difference.max.ms",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "max.compaction.lag.ms"
  {:name "max.compaction.lag.ms",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "preallocate"
  {:name "preallocate",
   :value "false",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.downconversion.enable"
  {:name "message.downconversion.enable",
   :value "true",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "max.message.bytes"
  {:name "max.message.bytes",
   :value "1000012",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.timestamp.type"
  {:name "message.timestamp.type",
   :value "CreateTime",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "retention.ms"
  {:name "retention.ms",
   :value "604800000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "min.cleanable.dirty.ratio"
  {:name "min.cleanable.dirty.ratio",
   :value "0.5",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.format.version"
  {:name "message.format.version",
   :value "2.4-IV1",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "compression.type"
  {:name "compression.type",
   :value "producer",
   :default? true,
   :read-only? false,
   :sensitive? false}},
 {:name "test3", :type :config-resource/topic}
 {"min.insync.replicas"
  {:name "min.insync.replicas",
   :value "1",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "follower.replication.throttled.replicas"
  {:name "follower.replication.throttled.replicas",
   :value "",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "flush.messages"
  {:name "flush.messages",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "leader.replication.throttled.replicas"
  {:name "leader.replication.throttled.replicas",
   :value "",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.bytes"
  {:name "segment.bytes",
   :value "1073741824",
   :default? false,
   :read-only? false,
   :sensitive? false},
  "flush.ms"
  {:name "flush.ms",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "unclean.leader.election.enable"
  {:name "unclean.leader.election.enable",
   :value "false",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "retention.bytes"
  {:name "retention.bytes",
   :value "-1",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "cleanup.policy"
  {:name "cleanup.policy",
   :value "compact",
   :default? false,
   :read-only? false,
   :sensitive? false},
  "file.delete.delay.ms"
  {:name "file.delete.delay.ms",
   :value "60000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.index.bytes"
  {:name "segment.index.bytes",
   :value "10485760",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "index.interval.bytes"
  {:name "index.interval.bytes",
   :value "4096",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "delete.retention.ms"
  {:name "delete.retention.ms",
   :value "86400000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.ms"
  {:name "segment.ms",
   :value "604800000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "min.compaction.lag.ms"
  {:name "min.compaction.lag.ms",
   :value "0",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "segment.jitter.ms"
  {:name "segment.jitter.ms",
   :value "0",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.timestamp.difference.max.ms"
  {:name "message.timestamp.difference.max.ms",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "max.compaction.lag.ms"
  {:name "max.compaction.lag.ms",
   :value "9223372036854775807",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "preallocate"
  {:name "preallocate",
   :value "false",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.downconversion.enable"
  {:name "message.downconversion.enable",
   :value "true",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "max.message.bytes"
  {:name "max.message.bytes",
   :value "1000012",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.timestamp.type"
  {:name "message.timestamp.type",
   :value "CreateTime",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "retention.ms"
  {:name "retention.ms",
   :value "604800000",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "min.cleanable.dirty.ratio"
  {:name "min.cleanable.dirty.ratio",
   :value "0.5",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "message.format.version"
  {:name "message.format.version",
   :value "2.4-IV1",
   :default? true,
   :read-only? false,
   :sensitive? false},
  "compression.type"
  {:name "compression.type",
   :value "producer",
   :default? true,
   :read-only? false,
   :sensitive? false}}}
