{"ssl.enabled.protocols"
 {:name "ssl.enabled.protocols",
  :value "TLSv1.2,TLSv1.1,TLSv1",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "advertised.host.name"
 {:name "advertised.host.name",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "socket.request.max.bytes"
 {:name "socket.request.max.bytes",
  :value "104857600",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "controller.socket.timeout.ms"
 {:name "controller.socket.timeout.ms",
  :value "30000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "min.insync.replicas"
 {:name "min.insync.replicas",
  :value "1",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "sasl.client.callback.handler.class"
 {:name "sasl.client.callback.handler.class",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "group.min.session.timeout.ms"
 {:name "group.min.session.timeout.ms",
  :value "6000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "controlled.shutdown.retry.backoff.ms"
 {:name "controlled.shutdown.retry.backoff.ms",
  :value "5000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "metrics.sample.window.ms"
 {:name "metrics.sample.window.ms",
  :value "30000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "replica.fetch.backoff.ms"
 {:name "replica.fetch.backoff.ms",
  :value "1000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "zookeeper.max.in.flight.requests"
 {:name "zookeeper.max.in.flight.requests",
  :value "10",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.message.timestamp.difference.max.ms"
 {:name "log.message.timestamp.difference.max.ms",
  :value "9223372036854775807",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "broker.id.generation.enable"
 {:name "broker.id.generation.enable",
  :value "true",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "password.encoder.secret"
 {:name "password.encoder.secret",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? true},
 "sasl.kerberos.ticket.renew.window.factor"
 {:name "sasl.kerberos.ticket.renew.window.factor",
  :value "0.8",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "transaction.state.log.min.isr"
 {:name "transaction.state.log.min.isr",
  :value "1",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "group.initial.rebalance.delay.ms"
 {:name "group.initial.rebalance.delay.ms",
  :value "0",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "host.name"
 {:name "host.name",
  :value "",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "alter.log.dirs.replication.quota.window.size.seconds"
 {:name "alter.log.dirs.replication.quota.window.size.seconds",
  :value "1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "inter.broker.protocol.version"
 {:name "inter.broker.protocol.version",
  :value "2.4-IV1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "delegation.token.expiry.check.interval.ms"
 {:name "delegation.token.expiry.check.interval.ms",
  :value "3600000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "zookeeper.connection.timeout.ms"
 {:name "zookeeper.connection.timeout.ms",
  :value "6000",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "replica.socket.receive.buffer.bytes"
 {:name "replica.socket.receive.buffer.bytes",
  :value "65536",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "max.connections"
 {:name "max.connections",
  :value "2147483647",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.cleaner.dedupe.buffer.size"
 {:name "log.cleaner.dedupe.buffer.size",
  :value "134217728",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "offsets.load.buffer.size"
 {:name "offsets.load.buffer.size",
  :value "5242880",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.endpoint.identification.algorithm"
 {:name "ssl.endpoint.identification.algorithm",
  :value "https",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "transaction.state.log.num.partitions"
 {:name "transaction.state.log.num.partitions",
  :value "50",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "max.incremental.fetch.session.cache.slots"
 {:name "max.incremental.fetch.session.cache.slots",
  :value "1000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "sasl.enabled.mechanisms"
 {:name "sasl.enabled.mechanisms",
  :value "GSSAPI",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "replica.fetch.min.bytes"
 {:name "replica.fetch.min.bytes",
  :value "1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "zookeeper.sync.time.ms"
 {:name "zookeeper.sync.time.ms",
  :value "2000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.segment.delete.delay.ms"
 {:name "log.segment.delete.delay.ms",
  :value "60000",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.cleaner.io.max.bytes.per.second"
 {:name "log.cleaner.io.max.bytes.per.second",
  :value "1.7976931348623157E308",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "unclean.leader.election.enable"
 {:name "unclean.leader.election.enable",
  :value "false",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "delete.records.purgatory.purge.interval.requests"
 {:name "delete.records.purgatory.purge.interval.requests",
  :value "1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.provider"
 {:name "ssl.provider",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "ssl.truststore.location"
 {:name "ssl.truststore.location",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "num.partitions"
 {:name "num.partitions",
  :value "1",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "password.encoder.key.length"
 {:name "password.encoder.key.length",
  :value "128",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "alter.log.dirs.replication.quota.window.num"
 {:name "alter.log.dirs.replication.quota.window.num",
  :value "11",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.cleaner.min.compaction.lag.ms"
 {:name "log.cleaner.min.compaction.lag.ms",
  :value "0",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "leader.imbalance.check.interval.seconds"
 {:name "leader.imbalance.check.interval.seconds",
  :value "300",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "broker.rack"
 {:name "broker.rack",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.key.password"
 {:name "ssl.key.password",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? true},
 "security.providers"
 {:name "security.providers",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.protocol"
 {:name "ssl.protocol",
  :value "TLS",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "request.timeout.ms"
 {:name "request.timeout.ms",
  :value "30000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "max.connections.per.ip"
 {:name "max.connections.per.ip",
  :value "2147483647",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "kafka.metrics.polling.interval.secs"
 {:name "kafka.metrics.polling.interval.secs",
  :value "10",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "leader.imbalance.per.broker.percentage"
 {:name "leader.imbalance.per.broker.percentage",
  :value "10",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.message.timestamp.type"
 {:name "log.message.timestamp.type",
  :value "CreateTime",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "background.threads"
 {:name "background.threads",
  :value "10",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "replica.lag.time.max.ms"
 {:name "replica.lag.time.max.ms",
  :value "10000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "default.replication.factor"
 {:name "default.replication.factor",
  :value "1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "quota.window.num"
 {:name "quota.window.num",
  :value "11",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "queued.max.request.bytes"
 {:name "queued.max.request.bytes",
  :value "-1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.keystore.password"
 {:name "ssl.keystore.password",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? true},
 "transaction.max.timeout.ms"
 {:name "transaction.max.timeout.ms",
  :value "900000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "alter.config.policy.class.name"
 {:name "alter.config.policy.class.name",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "sasl.login.class"
 {:name "sasl.login.class",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "sasl.login.refresh.window.jitter"
 {:name "sasl.login.refresh.window.jitter",
  :value "0.05",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "producer.purgatory.purge.interval.requests"
 {:name "producer.purgatory.purge.interval.requests",
  :value "1000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "connections.max.idle.ms"
 {:name "connections.max.idle.ms",
  :value "600000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.trustmanager.algorithm"
 {:name "ssl.trustmanager.algorithm",
  :value "PKIX",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "transaction.state.log.segment.bytes"
 {:name "transaction.state.log.segment.bytes",
  :value "104857600",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "auto.leader.rebalance.enable"
 {:name "auto.leader.rebalance.enable",
  :value "true",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "advertised.port"
 {:name "advertised.port",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "metrics.num.samples"
 {:name "metrics.num.samples",
  :value "2",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "controlled.shutdown.enable"
 {:name "controlled.shutdown.enable",
  :value "true",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "password.encoder.iterations"
 {:name "password.encoder.iterations",
  :value "4096",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "listener.security.protocol.map"
 {:name "listener.security.protocol.map",
  :value
  "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "queued.max.requests"
 {:name "queued.max.requests",
  :value "500",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.cleanup.policy"
 {:name "log.cleanup.policy",
  :value "delete",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "ssl.keystore.location"
 {:name "ssl.keystore.location",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "sasl.login.refresh.window.factor"
 {:name "sasl.login.refresh.window.factor",
  :value "0.8",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "sasl.login.callback.handler.class"
 {:name "sasl.login.callback.handler.class",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.cipher.suites"
 {:name "ssl.cipher.suites",
  :value "",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "transactional.id.expiration.ms"
 {:name "transactional.id.expiration.ms",
  :value "604800000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "client.quota.callback.class"
 {:name "client.quota.callback.class",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "kafka.metrics.reporters"
 {:name "kafka.metrics.reporters",
  :value "",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "transaction.remove.expired.transaction.cleanup.interval.ms"
 {:name "transaction.remove.expired.transaction.cleanup.interval.ms",
  :value "3600000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "password.encoder.keyfactory.algorithm"
 {:name "password.encoder.keyfactory.algorithm",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "connections.max.reauth.ms"
 {:name "connections.max.reauth.ms",
  :value "0",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "replication.quota.window.size.seconds"
 {:name "replication.quota.window.size.seconds",
  :value "1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.truststore.password"
 {:name "ssl.truststore.password",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? true},
 "log.cleaner.enable"
 {:name "log.cleaner.enable",
  :value "true",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "num.io.threads"
 {:name "num.io.threads",
  :value "8",
  :default? false,
  :read-only? false,
  :sensitive? false},
 "log.index.interval.bytes"
 {:name "log.index.interval.bytes",
  :value "4096",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "transaction.state.log.load.buffer.size"
 {:name "transaction.state.log.load.buffer.size",
  :value "5242880",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.flush.interval.messages"
 {:name "log.flush.interval.messages",
  :value "9223372036854775807",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "offsets.commit.required.acks"
 {:name "offsets.commit.required.acks",
  :value "-1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.roll.hours"
 {:name "log.roll.hours",
  :value "168",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.keymanager.algorithm"
 {:name "ssl.keymanager.algorithm",
  :value "SunX509",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.retention.check.interval.ms"
 {:name "log.retention.check.interval.ms",
  :value "300000",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "socket.receive.buffer.bytes"
 {:name "socket.receive.buffer.bytes",
  :value "102400",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "log.retention.minutes"
 {:name "log.retention.minutes",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "replica.fetch.response.max.bytes"
 {:name "replica.fetch.response.max.bytes",
  :value "10485760",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.principal.mapping.rules"
 {:name "ssl.principal.mapping.rules",
  :value "DEFAULT",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.keystore.type"
 {:name "ssl.keystore.type",
  :value "JKS",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "ssl.client.auth"
 {:name "ssl.client.auth",
  :value "none",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "socket.send.buffer.bytes"
 {:name "socket.send.buffer.bytes",
  :value "102400",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "replication.quota.window.num"
 {:name "replication.quota.window.num",
  :value "11",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.flush.interval.ms"
 {:name "log.flush.interval.ms",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "offsets.topic.replication.factor"
 {:name "offsets.topic.replication.factor",
  :value "1",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "control.plane.listener.name"
 {:name "control.plane.listener.name",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "create.topic.policy.class.name"
 {:name "create.topic.policy.class.name",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.message.downconversion.enable"
 {:name "log.message.downconversion.enable",
  :value "true",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "quota.producer.default"
 {:name "quota.producer.default",
  :value "9223372036854775807",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.cleaner.io.buffer.size"
 {:name "log.cleaner.io.buffer.size",
  :value "524288",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.flush.start.offset.checkpoint.interval.ms"
 {:name "log.flush.start.offset.checkpoint.interval.ms",
  :value "60000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "replica.fetch.max.bytes"
 {:name "replica.fetch.max.bytes",
  :value "1048576",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.cleaner.delete.retention.ms"
 {:name "log.cleaner.delete.retention.ms",
  :value "86400000",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "group.max.session.timeout.ms"
 {:name "group.max.session.timeout.ms",
  :value "1800000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "num.network.threads"
 {:name "num.network.threads",
  :value "3",
  :default? false,
  :read-only? false,
  :sensitive? false},
 "security.inter.broker.protocol"
 {:name "security.inter.broker.protocol",
  :value "PLAINTEXT",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "advertised.listeners"
 {:name "advertised.listeners",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "offsets.topic.segment.bytes"
 {:name "offsets.topic.segment.bytes",
  :value "104857600",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "zookeeper.connect"
 {:name "zookeeper.connect",
  :value "localhost:2181",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "num.recovery.threads.per.data.dir"
 {:name "num.recovery.threads.per.data.dir",
  :value "1",
  :default? false,
  :read-only? false,
  :sensitive? false},
 "reserved.broker.max.id"
 {:name "reserved.broker.max.id",
  :value "1000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "max.connections.per.ip.overrides"
 {:name "max.connections.per.ip.overrides",
  :value "",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.flush.scheduler.interval.ms"
 {:name "log.flush.scheduler.interval.ms",
  :value "9223372036854775807",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "group.max.size"
 {:name "group.max.size",
  :value "2147483647",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "fetch.purgatory.purge.interval.requests"
 {:name "fetch.purgatory.purge.interval.requests",
  :value "1000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "transaction.abort.timed.out.transaction.cleanup.interval.ms"
 {:name "transaction.abort.timed.out.transaction.cleanup.interval.ms",
  :value "60000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "offsets.topic.num.partitions"
 {:name "offsets.topic.num.partitions",
  :value "50",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.cleaner.max.compaction.lag.ms"
 {:name "log.cleaner.max.compaction.lag.ms",
  :value "9223372036854775807",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "auto.create.topics.enable"
 {:name "auto.create.topics.enable",
  :value "true",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.roll.jitter.ms"
 {:name "log.roll.jitter.ms",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "port"
 {:name "port",
  :value "9092",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "replica.high.watermark.checkpoint.interval.ms"
 {:name "replica.high.watermark.checkpoint.interval.ms",
  :value "5000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "quota.consumer.default"
 {:name "quota.consumer.default",
  :value "9223372036854775807",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "transaction.state.log.replication.factor"
 {:name "transaction.state.log.replication.factor",
  :value "1",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "log.cleaner.threads"
 {:name "log.cleaner.threads",
  :value "1",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "delete.topic.enable"
 {:name "delete.topic.enable",
  :value "true",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "replica.selector.class"
 {:name "replica.selector.class",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "metrics.recording.level"
 {:name "metrics.recording.level",
  :value "INFO",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.retention.hours"
 {:name "log.retention.hours",
  :value "168",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "sasl.kerberos.principal.to.local.rules"
 {:name "sasl.kerberos.principal.to.local.rules",
  :value "DEFAULT",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.message.format.version"
 {:name "log.message.format.version",
  :value "2.4-IV1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.roll.jitter.hours"
 {:name "log.roll.jitter.hours",
  :value "0",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "offset.metadata.max.bytes"
 {:name "offset.metadata.max.bytes",
  :value "4096",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "principal.builder.class"
 {:name "principal.builder.class",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "sasl.server.callback.handler.class"
 {:name "sasl.server.callback.handler.class",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "zookeeper.set.acl"
 {:name "zookeeper.set.acl",
  :value "false",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "connection.failed.authentication.delay.ms"
 {:name "connection.failed.authentication.delay.ms",
  :value "100",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.cleaner.backoff.ms"
 {:name "log.cleaner.backoff.ms",
  :value "15000",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "ssl.secure.random.implementation"
 {:name "ssl.secure.random.implementation",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.cleaner.io.buffer.load.factor"
 {:name "log.cleaner.io.buffer.load.factor",
  :value "0.9",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "sasl.login.refresh.min.period.seconds"
 {:name "sasl.login.refresh.min.period.seconds",
  :value "60",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "controlled.shutdown.max.retries"
 {:name "controlled.shutdown.max.retries",
  :value "3",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "authorizer.class.name"
 {:name "authorizer.class.name",
  :value "",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "broker.id"
 {:name "broker.id",
  :value "0",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "log.flush.offset.checkpoint.interval.ms"
 {:name "log.flush.offset.checkpoint.interval.ms",
  :value "60000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "zookeeper.session.timeout.ms"
 {:name "zookeeper.session.timeout.ms",
  :value "6000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.dir"
 {:name "log.dir",
  :value "/tmp/kafka-logs",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "offsets.topic.compression.codec"
 {:name "offsets.topic.compression.codec",
  :value "0",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "ssl.truststore.type"
 {:name "ssl.truststore.type",
  :value "JKS",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "message.max.bytes"
 {:name "message.max.bytes",
  :value "1000012",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "delegation.token.max.lifetime.ms"
 {:name "delegation.token.max.lifetime.ms",
  :value "604800000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.cleaner.min.cleanable.ratio"
 {:name "log.cleaner.min.cleanable.ratio",
  :value "0.5",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "quota.window.size.seconds"
 {:name "quota.window.size.seconds",
  :value "1",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "sasl.jaas.config"
 {:name "sasl.jaas.config",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? true},
 "delegation.token.expiry.time.ms"
 {:name "delegation.token.expiry.time.ms",
  :value "86400000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "password.encoder.old.secret"
 {:name "password.encoder.old.secret",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? true},
 "offsets.retention.check.interval.ms"
 {:name "offsets.retention.check.interval.ms",
  :value "600000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.retention.bytes"
 {:name "log.retention.bytes",
  :value "-1",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "replica.fetch.wait.max.ms"
 {:name "replica.fetch.wait.max.ms",
  :value "500",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.retention.ms"
 {:name "log.retention.ms",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "listeners"
 {:name "listeners",
  :value "PLAINTEXT://:9092",
  :default? false,
  :read-only? false,
  :sensitive? false},
 "offsets.commit.timeout.ms"
 {:name "offsets.commit.timeout.ms",
  :value "5000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "log.index.size.max.bytes"
 {:name "log.index.size.max.bytes",
  :value "10485760",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "sasl.kerberos.min.time.before.relogin"
 {:name "sasl.kerberos.min.time.before.relogin",
  :value "60000",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "sasl.mechanism.inter.broker.protocol"
 {:name "sasl.mechanism.inter.broker.protocol",
  :value "GSSAPI",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "inter.broker.listener.name"
 {:name "inter.broker.listener.name",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "replica.socket.timeout.ms"
 {:name "replica.socket.timeout.ms",
  :value "30000",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "sasl.kerberos.kinit.cmd"
 {:name "sasl.kerberos.kinit.cmd",
  :value "/usr/bin/kinit",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.dirs"
 {:name "log.dirs",
  :value "/tmp/kafka-logs",
  :default? false,
  :read-only? true,
  :sensitive? false},
 "sasl.kerberos.ticket.renew.jitter"
 {:name "sasl.kerberos.ticket.renew.jitter",
  :value "0.05",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "offsets.retention.minutes"
 {:name "offsets.retention.minutes",
  :value "10080",
  :default? true,
  :read-only? true,
  :sensitive? false},
 "num.replica.alter.log.dirs.threads"
 {:name "num.replica.alter.log.dirs.threads",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? false},
 "sasl.kerberos.service.name"
 {:name "sasl.kerberos.service.name",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.segment.bytes"
 {:name "log.segment.bytes",
  :value "1073741824",
  :default? false,
  :read-only? false,
  :sensitive? false},
 "compression.type"
 {:name "compression.type",
  :value "producer",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "num.replica.fetchers"
 {:name "num.replica.fetchers",
  :value "1",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "metric.reporters"
 {:name "metric.reporters",
  :value "",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "delegation.token.master.key"
 {:name "delegation.token.master.key",
  :value nil,
  :default? true,
  :read-only? true,
  :sensitive? true},
 "sasl.login.refresh.buffer.seconds"
 {:name "sasl.login.refresh.buffer.seconds",
  :value "300",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.preallocate"
 {:name "log.preallocate",
  :value "false",
  :default? true,
  :read-only? false,
  :sensitive? false},
 "log.roll.ms"
 {:name "log.roll.ms",
  :value nil,
  :default? true,
  :read-only? false,
  :sensitive? false},
 "password.encoder.cipher.algorithm"
 {:name "password.encoder.cipher.algorithm",
  :value "AES/CBC/PKCS5Padding",
  :default? true,
  :read-only? true,
  :sensitive? false}}
